config/routes.rb
Rails.application.routes.draw do

  resources :cart_items
  resources :ages
  resources :genders
  resources :sides
  resources :sizes
  resources :categories
  resources :found_items
  devise_for :users
  root to: "items#index"
  resources :items
  resources :charges

  get "/cart_items/new/:id" => "cart_items#new"
  get "/cart/:id" => "carts#show"
  get "/home" => "static#show"
  get "/about" => "static#about"

  get "/users/:id" => "users#show"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/age.rb
class Age < ActiveRecord::Base
  has_many :found_items
  has_many :items

  validates :name, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :items, :through => :cart_items
  has_many :users
  has_many :cart_items

  def subtotal

  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :item
  belongs_to :cart
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :found_items
  has_many :items

  validates :name, presence: true
end

app/models/found_item.rb
class FoundItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :size
  belongs_to :side
  belongs_to :gender
  belongs_to :age

  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader

  #validations of the new and edit forms for found items - location must be zip
  validates :name, :category_id, :location, :image1, presence: true
  validates :location, numericality: true
end

app/models/gender.rb
class Gender < ActiveRecord::Base
  has_many :found_items
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :size
  belongs_to :side
  belongs_to :gender
  belongs_to :age
  belongs_to :cart

  mount_uploader :image1, Image1Uploader
  mount_uploader :image2, Image2Uploader
  mount_uploader :image3, Image3Uploader

  #validations of the new and edit forms for items - price must be number
  validates :name, :price, :image1, :category_id, presence: true
  validates :price, numericality: true
end

app/models/side.rb
class Side < ActiveRecord::Base
  has_many :found_items
  has_many :items

  validates :name, presence: true
end

app/models/size.rb
class Size < ActiveRecord::Base
  has_many :found_items
  has_many :items

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :found_items
  has_many :items
  belongs_to :item

  mount_uploader :image_url, ImageUrlUploader
end

app/controllers/ages_controller.rb
class AgesController < ApplicationController
  before_action :set_age, only: [:show, :edit, :update, :destroy]

  # GET /ages
  # GET /ages.json
  def index
    @ages = Age.all
  end

  # GET /ages/1
  # GET /ages/1.json
  def show
  end

  # GET /ages/new
  def new
    @age = Age.new
  end

  # GET /ages/1/edit
  def edit
  end

  # POST /ages
  # POST /ages.json
  def create
    @age = Age.new(age_params)

    respond_to do |format|
      if @age.save
        format.html { redirect_to @age, notice: 'Age was successfully created.' }
        format.json { render :show, status: :created, location: @age }
      else
        format.html { render :new }
        format.json { render json: @age.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ages/1
  # PATCH/PUT /ages/1.json
  def update
    respond_to do |format|
      if @age.update(age_params)
        format.html { redirect_to @age, notice: 'Age was successfully updated.' }
        format.json { render :show, status: :ok, location: @age }
      else
        format.html { render :edit }
        format.json { render json: @age.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ages/1
  # DELETE /ages/1.json
  def destroy
    @age.destroy
    respond_to do |format|
      format.html { redirect_to ages_url, notice: 'Age was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_age
      @age = Age.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def age_params
      params.require(:age).permit(:found_id, :item_id, :name)
    end
end

app/helpers/ages_helper.rb
module AgesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/found_items_helper.rb
module FoundItemsHelper
end

app/helpers/genders_helper.rb
module GendersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sides_helper.rb
module SidesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/ages/_form.html.erb
<%= simple_form_for(@age) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :found_id %>
    <%= f.input :item_id %>
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ages/edit.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Age #<%= @age.id %></h3>
      </div>
      <div class="panel-body">
        <%= render 'form', age: @age %>
      </div>
    </div>
  </div>
</div>

app/views/ages/index.html.erb
<div class="page-header">
  <h1>
    Ages
    <%= link_to icon('plus'), new_age_path, class: "btn btn-lg btn-success" %>
  </h1>
</div>

<!-- Responsive, Isotope-based layout example -->

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Ages (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @ages.each do |age| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Age #<%= age.id %></h3>
      </div>
      <div class="panel-body">
        <dl>
          <dt>Found</dt>
          <dd><%= age.found_id %></dd>

          <dt>Item</dt>
          <dd><%= age.item_id %></dd>

          <dt>Name</dt>
          <dd><%= age.name %></dd>

        </dl>
        <div class="btn-group btn-group-justified">
          <%= link_to icon('search-plus'), age, class: "btn btn-primary" %>

          <%= link_to icon('edit'), edit_age_url(age), class: "btn btn-warning" %>

          <%= link_to icon('trash-o'), age, method: :delete, data: { confirm: "Do you really want to delete this age?" }, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/3.1.8/imagesloaded.pkgd.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container');

    $container.imagesLoaded(function() {
      $container.isotope({
        itemSelector: '.isotope-item',
        layoutMode: 'masonry',
        filter: function() {
          return qsRegex ? $(this).text().match( qsRegex ) : true;
        }
      })
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<!-- End responsive, Isotope-based layout example -->

app/views/ages/new.html.erb
<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Age</h3>
      </div>
      <div class="panel-body">
        <%= render 'form', age: @age %>
      </div>
    </div>
  </div>
</div>

app/views/ages/show.html.erb
<!-- Responsive panel example-->

<div class="row">
  <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Age #<%= @age.id %></h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <dl class="dl-horizontal">
              <dt>Found</dt>
              <dd><%= @age.found_id %></dd>

              <dt>Item</dt>
              <dd><%= @age.item_id %></dd>

              <dt>Name</dt>
              <dd><%= @age.name %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <%= link_to icon('chevron-left'), ages_path, class: "btn btn-primary" %>

              <%= link_to icon('edit'), edit_age_path(@age), class: "btn btn-warning" %>

              <%= link_to icon('trash-o'), @age, method: :delete, data: { confirm: "Do you really want to delete this age?" }, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End responsive panel example -->